- name: venafi_certificate_fake
  connection: local
  hosts: localhost
  tags:
    - fake
  tasks:
  - name: venafi_certificate
    venafi_certificate:
      test_mode: true
      common_name: 'testcert-ansible-fake-{{ 99999999 | random }}.example.com'
      path: "{{ }}"
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'


- name: venafi_certificate_tpp
  connection: local
  hosts: localhost
  tags:
    - tpp
  tasks:
  - name: venafi_certificate
    venafi_certificate:
      url: "{{ url }}"
      user: "{{ user }}"
      password: "{{ password }}"
      zone: "{{ user }}"
      path: "{{ user }}"
      common_name: 'testcert-ansible-tpp-{{ 99999999 | random }}.example.com'
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'

- name: venafi_certificate_cloud
  connection: local
  hosts: localhost
  tags:
    - cloud
  tasks:
  - name: venafi_certificate
    venafi_certificate:
      url: "{{ url }}"
      token: "{{ token }}"
      zone: "{{ zone }}"
      path: "{{ path }}"
      common_name: 'testcert-ansible-cloud-{{ 99999999 | random }}.example.com'
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'
