#Clone https://github.com/chrismeyersfsu/provision_docker.git to /etc/ansible/roles before run
---
- name: Bring up docker containers for docker connection inventory iface
  hosts: localhost
  roles:
    - role: provision_docker
      provision_docker_privileged: true,
      provision_docker_inventory_group: "{{ groups['robots'] }}"
      provision_docker_use_docker_connection: true

- hosts: robots
  tasks:
    - name: "Say hello to my new containers"
      ping:

    - name: "Install dependencies"
      apt:
        name:
          - python
          - python-pip
          - python-setuptools
        state: latest
        update_cache: True
    - name: "Install required pip packages"
      pip:
        name:
          - pyOpenSSL

    - name: "Create directories"
      file:
        path: /etc/ssl/{{ item.dir }}
        state: directory
        mode: 0755
      with_items:
        - { dir: 'csr' }
        - { dir: 'private' }


    # Testing original openssl module
    # Generate an OpenSSL Certificate Signing Request with Subject information
    - openssl_csr:
        path: /etc/ssl/csr/www.ansible.com.csr
        privatekey_path: /etc/ssl/private/ansible.com.pem
        privatekey_passphrase: ansible
        country_name: FR
        organization_name: Ansible
        email_address: jdoe@ansible.com
        common_name: www.ansible.com