- name: venafi_certificate_fake
  connection: local
  hosts: localhost
  tags:
    - fake
  tasks:
  - name: venafi_certificate
    venafi_certificate:
      test_mode: true
      common_name: 'testcert-ansible-fake-{{ 99999999 | random }}.example.com'
      path: "{{ path }}"
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'

