#Generater certificates on remote host
- name: venafi_certificate_cloud
  tasks:
  - name: venafi_certificate
    venafi_certificate:
      url: "{{ venafi.url }}"
      token: "{{ venafi.token }}"
      zone: "{{ venafi.zone }}"
      path: "{{ certificate.path }}"
      test_mode: "{{ venafi.test_mode }}"
      user: "{{ venafi.user }}"
      password: "{{ venafi.password }}"
      common_name: "{{ certificate.common_name }}"
    register: testout
  - name: "dump test output"
    debug:
      msg: "{{ testout }}"