#Generater certificates on remote host
- name: venafi_certificate_cloud
  tasks:
  - name: venafi_certificate
    venafi_certificate:
      url: "{{ url }}"
      token: "{{ token }}"
      zone: "{{ zone }}"
      path: "{{ path }}"
      test_mode: "{{ test_mode }}"
      user: "{{ user }}"
      password: "{{ password }}"
      common_name: '{{ common_name }}'
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'
