- name: venafi_certificate_tpp
  connection: local
  hosts: localhost
  tags:
    - tpp
  tasks:
  - name: venafi_certificate
    venafi_certificate:
      url: "{{ url }}"
      user: "{{ user }}"
      password: "{{ password }}"
      zone: "{{ user }}"
      path: "{{ user }}"
      common_name: '{{ common_name }}'
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'
