---
molecule:
  ignore_paths:
    - ../../.git
    - ../../.venv37
    - ../../venv27
    - ../../venv
    - ../../.molecule
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: python:3.7.10
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
